name: Scrape Kings League Infojobs Website

on:
  workflow_dispatch:

  repository_dispatch:
    types:
      - webhook

  schedule:
    - cron: "0 */1 * * 0"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: NPM dependency installation
        run: npm install
      - name: Scrapping Kings League web
        run: node scrapping/leaderboard.js
      - name: Adding new changes to staging area
        run: |
          git config user.name kings-league-bot
          git add -A
      - name: Verifying updated data & commiting
        run: if git diff-index --quiet HEAD;
              then git commit -m "[BOT] Nothing to commit, all data was up to date.";
              else git commit -m "[BOT] Updated Kings League Database.";
              fi
      - name: Pushing to main branch
        run: git push origin main
