name: Scrape Kings League Infojobs Website

on:
  workflow_dispatch:

  repository_dispatch:
    types:
      - webhook

  schedule:
    - cron: "15 16-21/1 * 1-3 0"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: NPM dependency installation
        run: npm install
      - name: Scrapping Kings League web
        run: node run scrape
      - name: Adding new changes to staging area
        run: |
          git config --global user.email "${GITHUB_ACTOR}"
          git config --global user.name "${GITHUB_ACTOR}@users.noreply.github.com"
          git add -A
      - name: Verifying updated data & commiting
        run: if git diff-index --quiet HEAD;
              then git commit --allow-empty -m "[BOT] Nothing to commit, all data was up to date. [no ci]";
              else git commit -m "[BOT] Updated Kings League Database.";
             fi
      - name: Pushing to main branch
        run: git push origin main
